package com.v2ray.ang.ui.alone.icons

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

/**
 * Exact ports of the prototype's own `<symbol id="i-…">` sprite (hand-drawn,
 * 24x24 viewBox, 1.7 stroke, round caps/joins) — not a swap-in for a generic
 * icon set. Every path below was generated by parsing the original SVG `d`
 * string with a real path parser (not eyeballed) and was checked by
 * rasterizing both the source SVG and this reconstruction side by side
 * before being copied in here, so the geometry is verified, not just typed
 * out by hand.
 *
 * Compose has no direct primitive for an SVG `<circle>`; ones the source
 * drew as `<circle>` (help/globe rings, cast's center dot, pad's two dots)
 * are the standard two-arc / two-semicircle decomposition of that same
 * circle — confirmed identical to the original by the same render check.
 */
object Icons {
    object Alone {
        private var _power: ImageVector? = null
        private var _shield: ImageVector? = null
        private var _shieldOff: ImageVector? = null
        private var _terminal: ImageVector? = null
        private var _help: ImageVector? = null
        private var _globe: ImageVector? = null
        private var _chevron: ImageVector? = null
        private var _pulse: ImageVector? = null
        private var _pad: ImageVector? = null
        private var _cast: ImageVector? = null
        private var _fingerprint: ImageVector? = null
        private var _lang: ImageVector? = null
        private var _sun: ImageVector? = null
        private var _moon: ImageVector? = null
        private var _monitor: ImageVector? = null
        private var _bell: ImageVector? = null
        private var _lock: ImageVector? = null
        private var _check: ImageVector? = null

        /** i-power */
        val Power: ImageVector
            get() = _power ?: ImageVector.Builder(
                name = "AlonePower", defaultWidth = 24.dp, defaultHeight = 24.dp,
                viewportWidth = 24f, viewportHeight = 24f,
            ).path(
                stroke = SolidColor(Color.Black), strokeLineWidth = 1.7f,
                strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, fill = null,
            ) {
                moveTo(12f, 3f); lineTo(12f, 11.6f)
                moveTo(18.4f, 6.6f); arcTo(9f, 9f, 0f, true, true, 5.6f, 6.6f)
            }.build().also { _power = it }

        /** i-shield — the ConnectDial "connected" icon */
        val Shield: ImageVector
            get() = _shield ?: ImageVector.Builder(
                name = "AloneShield", defaultWidth = 24.dp, defaultHeight = 24.dp,
                viewportWidth = 24f, viewportHeight = 24f,
            ).path(
                stroke = SolidColor(Color.Black), strokeLineWidth = 1.7f,
                strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, fill = null,
            ) {
                moveTo(12f, 3.2f); lineTo(5f, 6.1f); lineTo(5f, 11.8f)
                curveTo(5f, 16.2f, 8f, 19.5f, 12f, 21f)
                curveTo(16f, 19.5f, 19f, 16.2f, 19f, 11.8f)
                lineTo(19f, 6.1f); lineTo(12f, 3.2f)
                moveTo(9.1f, 12.2f); lineTo(11.4f, 14.5f); lineTo(15.8f, 9.9f)
            }.build().also { _shield = it }

        /** i-shield-off — reserved for a future "protection paused" state; not used on Home yet. */
        val ShieldOff: ImageVector
            get() = _shieldOff ?: ImageVector.Builder(
                name = "AloneShieldOff", defaultWidth = 24.dp, defaultHeight = 24.dp,
                viewportWidth = 24f, viewportHeight = 24f,
            ).path(
                stroke = SolidColor(Color.Black), strokeLineWidth = 1.7f,
                strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, fill = null,
            ) {
                moveTo(12f, 3.2f); lineTo(5f, 6.1f); lineTo(5f, 11.8f)
                curveTo(5f, 16.2f, 8f, 19.5f, 12f, 21f)
                curveTo(16f, 19.5f, 19f, 16.2f, 19f, 11.8f)
                lineTo(19f, 6.1f); lineTo(12f, 3.2f)
                moveTo(9.6f, 9.6f); lineTo(14.4f, 14.4f)
                moveTo(14.4f, 9.6f); lineTo(9.6f, 14.4f)
            }.build().also { _shieldOff = it }

        /** i-terminal */
        val Terminal: ImageVector
            get() = _terminal ?: ImageVector.Builder(
                name = "AloneTerminal", defaultWidth = 24.dp, defaultHeight = 24.dp,
                viewportWidth = 24f, viewportHeight = 24f,
            ).path(
                stroke = SolidColor(Color.Black), strokeLineWidth = 1.7f,
                strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, fill = null,
            ) {
                moveTo(2.8f, 4.2f); lineTo(21.2f, 4.2f); lineTo(21.2f, 19.8f); lineTo(2.8f, 19.8f); lineTo(2.8f, 4.2f)
                moveTo(6.6f, 9.6f); lineTo(9.2f, 12.2f); lineTo(6.6f, 14.8f)
                moveTo(11.8f, 14.8f); lineTo(16.8f, 14.8f)
            }.build().also { _terminal = it }

        /** i-help */
        val Help: ImageVector
            get() = _help ?: ImageVector.Builder(
                name = "AloneHelp", defaultWidth = 24.dp, defaultHeight = 24.dp,
                viewportWidth = 24f, viewportHeight = 24f,
            ).path(
                stroke = SolidColor(Color.Black), strokeLineWidth = 1.7f,
                strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, fill = null,
            ) {
                moveTo(3f, 12f); arcTo(9f, 9f, 0f, true, false, 21f, 12f); arcTo(9f, 9f, 0f, true, false, 3f, 12f)
                moveTo(9.6f, 9.6f); arcTo(2.5f, 2.5f, 0f, true, true, 12.6f, 12.1f); lineTo(12.6f, 13.4f)
                moveTo(12f, 16.6f); lineTo(12f, 16.7f)
            }.build().also { _help = it }

        /** i-globe — ActiveServerCard */
        val Globe: ImageVector
            get() = _globe ?: ImageVector.Builder(
                name = "AloneGlobe", defaultWidth = 24.dp, defaultHeight = 24.dp,
                viewportWidth = 24f, viewportHeight = 24f,
            ).path(
                stroke = SolidColor(Color.Black), strokeLineWidth = 1.7f,
                strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, fill = null,
            ) {
                moveTo(3f, 12f); arcTo(9f, 9f, 0f, true, false, 21f, 12f); arcTo(9f, 9f, 0f, true, false, 3f, 12f)
                moveTo(3f, 12f); lineTo(21f, 12f)
                moveTo(12f, 3f); curveTo(14.9f, 6.4f, 14.9f, 17.2f, 12f, 21f)
                moveTo(12f, 3f); curveTo(9.1f, 6.4f, 9.1f, 17.2f, 12f, 21f)
            }.build().also { _globe = it }

        /** i-chev — `.flip`'d (autoMirrored) at the call site for RTL, per the prototype's own convention. */
        val Chevron: ImageVector
            get() = _chevron ?: ImageVector.Builder(
                name = "AloneChevron", defaultWidth = 24.dp, defaultHeight = 24.dp,
                viewportWidth = 24f, viewportHeight = 24f, autoMirror = true,
            ).path(
                stroke = SolidColor(Color.Black), strokeLineWidth = 1.7f,
                strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, fill = null,
            ) {
                moveTo(14.4f, 6.4f); lineTo(8.8f, 12f); lineTo(14.4f, 17.6f)
            }.build().also { _chevron = it }

        /** i-pulse — latency tile */
        val Pulse: ImageVector
            get() = _pulse ?: ImageVector.Builder(
                name = "AlonePulse", defaultWidth = 24.dp, defaultHeight = 24.dp,
                viewportWidth = 24f, viewportHeight = 24f,
            ).path(
                stroke = SolidColor(Color.Black), strokeLineWidth = 1.7f,
                strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, fill = null,
            ) {
                moveTo(3f, 12f); lineTo(6.6f, 12f); lineTo(8.6f, 6.8f); lineTo(11.6f, 17.2f); lineTo(14f, 12f); lineTo(21f, 12f)
            }.build().also { _pulse = it }

        /** i-pad — DNS tile (rounded toggle body + two dots, drawn as a second filled path) */
        val Pad: ImageVector
            get() = _pad ?: ImageVector.Builder(
                name = "AlonePad", defaultWidth = 24.dp, defaultHeight = 24.dp,
                viewportWidth = 24f, viewportHeight = 24f,
            ).path(
                stroke = SolidColor(Color.Black), strokeLineWidth = 1.7f,
                strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, fill = null,
            ) {
                moveTo(7f, 8f); lineTo(17f, 8f); arcTo(4.5f, 4.5f, 0f, false, true, 17f, 17f); lineTo(7f, 17f)
                arcTo(4.5f, 4.5f, 0f, false, true, 7f, 8f)
                moveTo(7f, 11f); lineTo(7f, 14f)
                moveTo(5.5f, 12.5f); lineTo(8.5f, 12.5f)
            }.path(
                stroke = null, fill = SolidColor(Color.Black),
            ) {
                // two small filled dots, r=.95, at (16,11.9) and (18.1,14.3)
                moveTo(15.05f, 11.9f); arcTo(.95f, .95f, 0f, true, true, 16.95f, 11.9f); arcTo(.95f, .95f, 0f, true, true, 15.05f, 11.9f)
                moveTo(17.15f, 14.3f); arcTo(.95f, .95f, 0f, true, true, 19.05f, 14.3f); arcTo(.95f, .95f, 0f, true, true, 17.15f, 14.3f)
            }.build().also { _pad = it }

        /** i-cast — import/scan tile (concentric arcs + filled center dot) */
        val Cast: ImageVector
            get() = _cast ?: ImageVector.Builder(
                name = "AloneCast", defaultWidth = 24.dp, defaultHeight = 24.dp,
                viewportWidth = 24f, viewportHeight = 24f,
            ).path(
                stroke = null, fill = SolidColor(Color.Black),
            ) {
                // center dot r=2.1 at (12,12)
                moveTo(9.9f, 12f); arcTo(2.1f, 2.1f, 0f, true, true, 14.1f, 12f); arcTo(2.1f, 2.1f, 0f, true, true, 9.9f, 12f)
            }.path(
                stroke = SolidColor(Color.Black), strokeLineWidth = 1.7f,
                strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, fill = null,
            ) {
                moveTo(8.6f, 8.6f); arcTo(4.8f, 4.8f, 0f, false, false, 8.6f, 15.4f)
                moveTo(15.4f, 15.4f); arcTo(4.8f, 4.8f, 0f, false, false, 15.4f, 8.6f)
                moveTo(5.9f, 5.9f); arcTo(8.6f, 8.6f, 0f, false, false, 5.9f, 18.1f)
                moveTo(18.1f, 18.1f); arcTo(8.6f, 8.6f, 0f, false, false, 18.1f, 5.9f)
            }.build().also { _cast = it }

        /** i-fingerprint — Splash */
        val Fingerprint: ImageVector
            get() = _fingerprint ?: ImageVector.Builder(
                name = "AloneFingerprint", defaultWidth = 24.dp, defaultHeight = 24.dp,
                viewportWidth = 24f, viewportHeight = 24f,
            ).path(
                stroke = SolidColor(Color.Black), strokeLineWidth = 1.7f,
                strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, fill = null,
            ) {
                moveTo(12f, 21.2f)
                curveTo(10.1f, 18.6f, 9.5f, 15.3f, 9.5f, 12.3f)
                curveTo(9.5f, 10.8f, 10.6f, 9.6f, 12f, 9.6f)
                curveTo(13.4f, 9.6f, 14.5f, 10.8f, 14.5f, 12.3f)
                curveTo(14.5f, 14.6f, 14.1f, 16.9f, 15.1f, 18.7f)
                moveTo(6.5f, 18.6f)
                curveTo(5.3f, 16.2f, 5.1f, 13.4f, 5.1f, 12f)
                arcTo(6.9f, 6.9f, 0f, false, true, 18.9f, 12f)
                curveTo(18.9f, 13.4f, 18.8f, 15.5f, 18.1f, 17.5f)
                moveTo(3.5f, 8.5f)
                arcTo(9.5f, 9.5f, 0f, false, true, 12f, 3.2f)
                curveTo(15.6f, 3.2f, 18.7f, 5.2f, 20.5f, 8.5f)
            }.build().also { _fingerprint = it }

        /** i-lang — Language screen */
        val Lang: ImageVector
            get() = _lang ?: ImageVector.Builder(
                name = "AloneLang", defaultWidth = 24.dp, defaultHeight = 24.dp,
                viewportWidth = 24f, viewportHeight = 24f,
            ).path(
                stroke = SolidColor(Color.Black), strokeLineWidth = 1.7f,
                strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, fill = null,
            ) {
                moveTo(3f, 5.6f); lineTo(11.6f, 5.6f)
                moveTo(7.3f, 5.6f); lineTo(7.3f, 3.4f)
                moveTo(10f, 5.6f); curveTo(10f, 9.7f, 7.1f, 13.1f, 3.4f, 14.5f)
                moveTo(4.9f, 10.4f); curveTo(6.1f, 13f, 8.4f, 14.9f, 11.1f, 15.7f)
                moveTo(13.1f, 20.6f); lineTo(17f, 10.8f); lineTo(20.9f, 20.6f)
                moveTo(14.5f, 17.4f); lineTo(19.3f, 17.4f)
            }.build().also { _lang = it }

        /** i-sun — appearance mode toggle */
        val Sun: ImageVector
            get() = _sun ?: ImageVector.Builder(
                name = "AloneSun", defaultWidth = 24.dp, defaultHeight = 24.dp,
                viewportWidth = 24f, viewportHeight = 24f,
            ).path(
                stroke = SolidColor(Color.Black), strokeLineWidth = 1.7f,
                strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, fill = null,
            ) {
                moveTo(7.8f, 12f)
                arcTo(4.2f, 4.2f, 0f, true, false, 16.2f, 12f)
                arcTo(4.2f, 4.2f, 0f, true, false, 7.8f, 12f)
                moveTo(12f, 2.6f); lineTo(12f, 4.8f)
                moveTo(12f, 19.2f); lineTo(12f, 21.4f)
                moveTo(2.6f, 12f); lineTo(4.8f, 12f)
                moveTo(19.2f, 12f); lineTo(21.4f, 12f)
                moveTo(5.4f, 5.4f); lineTo(7f, 7f)
                moveTo(17f, 17f); lineTo(18.6f, 18.6f)
                moveTo(18.6f, 5.4f); lineTo(17f, 7f)
                moveTo(7f, 17f); lineTo(5.4f, 18.6f)
            }.build().also { _sun = it }

        /** i-moon — appearance mode toggle */
        val Moon: ImageVector
            get() = _moon ?: ImageVector.Builder(
                name = "AloneMoon", defaultWidth = 24.dp, defaultHeight = 24.dp,
                viewportWidth = 24f, viewportHeight = 24f,
            ).path(
                stroke = SolidColor(Color.Black), strokeLineWidth = 1.7f,
                strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, fill = null,
            ) {
                moveTo(20.4f, 14.6f)
                arcTo(8.8f, 8.8f, 0f, false, true, 9.4f, 3.6f)
                arcTo(8.8f, 8.8f, 0f, true, false, 20.4f, 14.6f)
            }.build().also { _moon = it }

        /** i-monitor — appearance mode toggle ("system") */
        val Monitor: ImageVector
            get() = _monitor ?: ImageVector.Builder(
                name = "AloneMonitor", defaultWidth = 24.dp, defaultHeight = 24.dp,
                viewportWidth = 24f, viewportHeight = 24f,
            ).path(
                stroke = SolidColor(Color.Black), strokeLineWidth = 1.7f,
                strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, fill = null,
            ) {
                moveTo(2.8f, 4.4f); lineTo(21.2f, 4.4f); lineTo(21.2f, 16.8f); lineTo(2.8f, 16.8f); lineTo(2.8f, 4.4f)
                moveTo(8.6f, 20.4f); lineTo(15.4f, 20.4f)
                moveTo(12f, 16.8f); lineTo(12f, 20.4f)
            }.build().also { _monitor = it }

        /** i-bell — notification onboarding step */
        val Bell: ImageVector
            get() = _bell ?: ImageVector.Builder(
                name = "AloneBell", defaultWidth = 24.dp, defaultHeight = 24.dp,
                viewportWidth = 24f, viewportHeight = 24f,
            ).path(
                stroke = SolidColor(Color.Black), strokeLineWidth = 1.7f,
                strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, fill = null,
            ) {
                moveTo(6.6f, 10.7f)
                arcTo(5.4f, 5.4f, 0f, false, true, 17.4f, 10.7f)
                curveTo(17.4f, 14.6f, 18.8f, 15.6f, 19.3f, 16.2f)
                lineTo(4.7f, 16.2f)
                curveTo(5.2f, 15.6f, 6.6f, 14.6f, 6.6f, 10.7f)
                moveTo(9.9f, 19.1f)
                arcTo(2.3f, 2.3f, 0f, false, false, 14.1f, 19.1f)
            }.build().also { _bell = it }

        /** i-lock — VPN permission onboarding step */
        val Lock: ImageVector
            get() = _lock ?: ImageVector.Builder(
                name = "AloneLock", defaultWidth = 24.dp, defaultHeight = 24.dp,
                viewportWidth = 24f, viewportHeight = 24f,
            ).path(
                stroke = SolidColor(Color.Black), strokeLineWidth = 1.7f,
                strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, fill = null,
            ) {
                moveTo(4.6f, 10.4f); lineTo(19.4f, 10.4f); lineTo(19.4f, 20.2f); lineTo(4.6f, 20.2f); lineTo(4.6f, 10.4f)
                moveTo(8.2f, 10.4f); lineTo(8.2f, 8f)
                arcTo(3.8f, 3.8f, 0f, false, true, 15.8f, 8f)
                lineTo(15.8f, 10.4f)
            }.build().also { _lock = it }

        /** i-check — permission-granted confirmation row */
        val Check: ImageVector
            get() = _check ?: ImageVector.Builder(
                name = "AloneCheck", defaultWidth = 24.dp, defaultHeight = 24.dp,
                viewportWidth = 24f, viewportHeight = 24f,
            ).path(
                stroke = SolidColor(Color.Black), strokeLineWidth = 1.7f,
                strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, fill = null,
            ) {
                moveTo(5f, 12.8f); lineTo(9.6f, 17.4f); lineTo(19f, 6.6f)
            }.build().also { _check = it }
    }
}
